# Validation data from the Daily Weather Reports

stations<-data.frame(name=c("Sumburgh Head",
                            "Stornoway",
                            "Malin Head",
                            "Blacksod Pt.",
                            "Valentia",
                            "Roche's Pt.",
                            "Parsonstown",
                            "Donaghadee",
                            "Liverpool Obsy.",
                            "Holyhead",
                            "Pembroke (St. Ann's)",
                            "Scilly (St. Mary's)",
                            "Jersey (St. Aubin's)",
                            "Portland Bill",
                            "Dungeness",
                            "Wick",
                            "Nairn",
                            "Aberdeen",
                            "Leith",
                            "North Shields",
                            "Spurn Head",
                            "Yarmouth",
                            "Loughborough",
                            "Oxford",
                            "London (Brixton)",
                            "Newton Reigny",
                            "Bath"),
                     latitude=c(59.86829,
                                58.19048,
                                55.36596,
                                54.09,
                                51.93971,
                                51.799,
                                53.02898,
                                54.64585,
                                53.40423,
                                53.31656,
                                51.68237,
                                49.92856,
                                49.184,
                                50.513,
                                50.91221,
                                58.43328,
                                57.58729,
                                57.1639,
                                55.96334,
                                55.00333,
                                53.5801,
                                52.61591,
                                52.78346,
                                51.76073,
                                51.45213,
                                54.6,
                                51.36423),
                     longitude=c(-1.27848,
                                 -6.37003,
                                 -7.333,
                                 -10.06,
                                 -10.24443,
                                 -8.24993,
                                 -7.88299,
                                 -5.5443,
                                 -2.99286,
                                 -4.62441,
                                 -5.17416,
                                 -6.30215,
                                 -2.161,
                                 -2.45561,
                                  0.97345,
                                 -3.07046,
                                 -3.89202,
                                 -2.10087,
                                 -3.17592,
                                 -1.42461,
                                  0.12247,
                                  1.73345,
                                 -1.2136,
                                 -1.2625,
                                 -0.12165,
                                 -2.8,
                                 -2.31891))

mslp<-data.frame('1903-02-07:18'=c(28.82,
                                   29.12,
                                   29.23,
                                   29.47,
                                   29.78,
                                   29.85,
                                   26.68,
                                   29.44,
                                   29.71,
                                   29.70,
                                   29.89,
                                   30.03,
                                   30.22,
                                   30.09,
                                   30.08
                                   29.04,
                                   29.11,
                                   29.11,
                                   29.24,
                                   29.39,
                                   29.72,
                                   29.89,
                                   NA,
                                   29.98,
                                   30.01,
                                   29.61,
                                   30.30))
